/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package images

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ImagesUploadInitPostRequest - struct for ImagesUploadInitPostRequest
type ImagesUploadInitPostRequest struct {
	InternalImagesHandlerUploadInitRequest *InternalImagesHandlerUploadInitRequest
	MapmapOfStringAny *map[string]interface{}
}

// InternalImagesHandlerUploadInitRequestAsImagesUploadInitPostRequest is a convenience function that returns InternalImagesHandlerUploadInitRequest wrapped in ImagesUploadInitPostRequest
func InternalImagesHandlerUploadInitRequestAsImagesUploadInitPostRequest(v *InternalImagesHandlerUploadInitRequest) ImagesUploadInitPostRequest {
	return ImagesUploadInitPostRequest{
		InternalImagesHandlerUploadInitRequest: v,
	}
}

// map[string]interface{}AsImagesUploadInitPostRequest is a convenience function that returns map[string]interface{} wrapped in ImagesUploadInitPostRequest
func MapmapOfStringAnyAsImagesUploadInitPostRequest(v *map[string]interface{}) ImagesUploadInitPostRequest {
	return ImagesUploadInitPostRequest{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ImagesUploadInitPostRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InternalImagesHandlerUploadInitRequest
	err = newStrictDecoder(data).Decode(&dst.InternalImagesHandlerUploadInitRequest)
	if err == nil {
		jsonInternalImagesHandlerUploadInitRequest, _ := json.Marshal(dst.InternalImagesHandlerUploadInitRequest)
		if string(jsonInternalImagesHandlerUploadInitRequest) == "{}" { // empty struct
			dst.InternalImagesHandlerUploadInitRequest = nil
		} else {
			if err = validator.Validate(dst.InternalImagesHandlerUploadInitRequest); err != nil {
				dst.InternalImagesHandlerUploadInitRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.InternalImagesHandlerUploadInitRequest = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InternalImagesHandlerUploadInitRequest = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ImagesUploadInitPostRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ImagesUploadInitPostRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ImagesUploadInitPostRequest) MarshalJSON() ([]byte, error) {
	if src.InternalImagesHandlerUploadInitRequest != nil {
		return json.Marshal(&src.InternalImagesHandlerUploadInitRequest)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ImagesUploadInitPostRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.InternalImagesHandlerUploadInitRequest != nil {
		return obj.InternalImagesHandlerUploadInitRequest
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ImagesUploadInitPostRequest) GetActualInstanceValue() (interface{}) {
	if obj.InternalImagesHandlerUploadInitRequest != nil {
		return *obj.InternalImagesHandlerUploadInitRequest
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableImagesUploadInitPostRequest struct {
	value *ImagesUploadInitPostRequest
	isSet bool
}

func (v NullableImagesUploadInitPostRequest) Get() *ImagesUploadInitPostRequest {
	return v.value
}

func (v *NullableImagesUploadInitPostRequest) Set(val *ImagesUploadInitPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImagesUploadInitPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImagesUploadInitPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImagesUploadInitPostRequest(val *ImagesUploadInitPostRequest) *NullableImagesUploadInitPostRequest {
	return &NullableImagesUploadInitPostRequest{value: val, isSet: true}
}

func (v NullableImagesUploadInitPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImagesUploadInitPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


