/*
RIXL API

Testing VideosAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rixl

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/rixl"
)

func Test_rixl_VideosAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VideosAPIService VideosGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.VideosGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosLanguagesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.VideosLanguagesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosUploadCompletePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.VideosUploadCompletePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosUploadInitPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.VideosUploadInitPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdAudioTracksDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdAudioTracksDelete(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdAudioTracksLangCodeDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var langCode string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdAudioTracksLangCodeDelete(context.Background(), videoId, langCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdAudioTracksLangCodePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var langCode string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdAudioTracksLangCodePut(context.Background(), videoId, langCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdAudioTracksPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdAudioTracksPost(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdAudioTracksTrackIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var trackId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdAudioTracksTrackIdDelete(context.Background(), videoId, trackId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdChaptersDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdChaptersDelete(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdChaptersPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdChaptersPut(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdDeleteDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		httpRes, err := apiClient.VideosAPI.VideosVideoIdDeleteDelete(context.Background(), videoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdGet(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdSubtitlesDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdSubtitlesDelete(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdSubtitlesLangCodeDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var langCode string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdSubtitlesLangCodeDelete(context.Background(), videoId, langCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdSubtitlesLangCodePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var langCode string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdSubtitlesLangCodePut(context.Background(), videoId, langCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdSubtitlesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdSubtitlesPost(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdSubtitlesSubtitleIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var subtitleId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdSubtitlesSubtitleIdDelete(context.Background(), videoId, subtitleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService VideosVideoIdThumbnailPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.VideosVideoIdThumbnailPut(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
