/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// VideosVideoIdChaptersPutRequest - struct for VideosVideoIdChaptersPutRequest
type VideosVideoIdChaptersPutRequest struct {
	UpdateChaptersRequest *UpdateChaptersRequest
	MapmapOfStringAny *map[string]interface{}
}

// UpdateChaptersRequestAsVideosVideoIdChaptersPutRequest is a convenience function that returns UpdateChaptersRequest wrapped in VideosVideoIdChaptersPutRequest
func UpdateChaptersRequestAsVideosVideoIdChaptersPutRequest(v *UpdateChaptersRequest) VideosVideoIdChaptersPutRequest {
	return VideosVideoIdChaptersPutRequest{
		UpdateChaptersRequest: v,
	}
}

// map[string]interface{}AsVideosVideoIdChaptersPutRequest is a convenience function that returns map[string]interface{} wrapped in VideosVideoIdChaptersPutRequest
func MapmapOfStringAnyAsVideosVideoIdChaptersPutRequest(v *map[string]interface{}) VideosVideoIdChaptersPutRequest {
	return VideosVideoIdChaptersPutRequest{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *VideosVideoIdChaptersPutRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into UpdateChaptersRequest
	err = newStrictDecoder(data).Decode(&dst.UpdateChaptersRequest)
	if err == nil {
		jsonUpdateChaptersRequest, _ := json.Marshal(dst.UpdateChaptersRequest)
		if string(jsonUpdateChaptersRequest) == "{}" { // empty struct
			dst.UpdateChaptersRequest = nil
		} else {
			if err = validator.Validate(dst.UpdateChaptersRequest); err != nil {
				dst.UpdateChaptersRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.UpdateChaptersRequest = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.UpdateChaptersRequest = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(VideosVideoIdChaptersPutRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(VideosVideoIdChaptersPutRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VideosVideoIdChaptersPutRequest) MarshalJSON() ([]byte, error) {
	if src.UpdateChaptersRequest != nil {
		return json.Marshal(&src.UpdateChaptersRequest)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VideosVideoIdChaptersPutRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.UpdateChaptersRequest != nil {
		return obj.UpdateChaptersRequest
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj VideosVideoIdChaptersPutRequest) GetActualInstanceValue() (interface{}) {
	if obj.UpdateChaptersRequest != nil {
		return *obj.UpdateChaptersRequest
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableVideosVideoIdChaptersPutRequest struct {
	value *VideosVideoIdChaptersPutRequest
	isSet bool
}

func (v NullableVideosVideoIdChaptersPutRequest) Get() *VideosVideoIdChaptersPutRequest {
	return v.value
}

func (v *NullableVideosVideoIdChaptersPutRequest) Set(val *VideosVideoIdChaptersPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVideosVideoIdChaptersPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVideosVideoIdChaptersPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideosVideoIdChaptersPutRequest(val *VideosVideoIdChaptersPutRequest) *NullableVideosVideoIdChaptersPutRequest {
	return &NullableVideosVideoIdChaptersPutRequest{value: val, isSet: true}
}

func (v NullableVideosVideoIdChaptersPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideosVideoIdChaptersPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


