/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ImagesUploadCompletePostRequest - struct for ImagesUploadCompletePostRequest
type ImagesUploadCompletePostRequest struct {
	InternalImagesHandlerCompleteRequest *InternalImagesHandlerCompleteRequest
	MapmapOfStringAny *map[string]interface{}
}

// InternalImagesHandlerCompleteRequestAsImagesUploadCompletePostRequest is a convenience function that returns InternalImagesHandlerCompleteRequest wrapped in ImagesUploadCompletePostRequest
func InternalImagesHandlerCompleteRequestAsImagesUploadCompletePostRequest(v *InternalImagesHandlerCompleteRequest) ImagesUploadCompletePostRequest {
	return ImagesUploadCompletePostRequest{
		InternalImagesHandlerCompleteRequest: v,
	}
}

// map[string]interface{}AsImagesUploadCompletePostRequest is a convenience function that returns map[string]interface{} wrapped in ImagesUploadCompletePostRequest
func MapmapOfStringAnyAsImagesUploadCompletePostRequest(v *map[string]interface{}) ImagesUploadCompletePostRequest {
	return ImagesUploadCompletePostRequest{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ImagesUploadCompletePostRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InternalImagesHandlerCompleteRequest
	err = newStrictDecoder(data).Decode(&dst.InternalImagesHandlerCompleteRequest)
	if err == nil {
		jsonInternalImagesHandlerCompleteRequest, _ := json.Marshal(dst.InternalImagesHandlerCompleteRequest)
		if string(jsonInternalImagesHandlerCompleteRequest) == "{}" { // empty struct
			dst.InternalImagesHandlerCompleteRequest = nil
		} else {
			if err = validator.Validate(dst.InternalImagesHandlerCompleteRequest); err != nil {
				dst.InternalImagesHandlerCompleteRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.InternalImagesHandlerCompleteRequest = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InternalImagesHandlerCompleteRequest = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ImagesUploadCompletePostRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ImagesUploadCompletePostRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ImagesUploadCompletePostRequest) MarshalJSON() ([]byte, error) {
	if src.InternalImagesHandlerCompleteRequest != nil {
		return json.Marshal(&src.InternalImagesHandlerCompleteRequest)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ImagesUploadCompletePostRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.InternalImagesHandlerCompleteRequest != nil {
		return obj.InternalImagesHandlerCompleteRequest
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ImagesUploadCompletePostRequest) GetActualInstanceValue() (interface{}) {
	if obj.InternalImagesHandlerCompleteRequest != nil {
		return *obj.InternalImagesHandlerCompleteRequest
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableImagesUploadCompletePostRequest struct {
	value *ImagesUploadCompletePostRequest
	isSet bool
}

func (v NullableImagesUploadCompletePostRequest) Get() *ImagesUploadCompletePostRequest {
	return v.value
}

func (v *NullableImagesUploadCompletePostRequest) Set(val *ImagesUploadCompletePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImagesUploadCompletePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImagesUploadCompletePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImagesUploadCompletePostRequest(val *ImagesUploadCompletePostRequest) *NullableImagesUploadCompletePostRequest {
	return &NullableImagesUploadCompletePostRequest{value: val, isSet: true}
}

func (v NullableImagesUploadCompletePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImagesUploadCompletePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


