/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// VideosUploadCompletePostRequest - struct for VideosUploadCompletePostRequest
type VideosUploadCompletePostRequest struct {
	GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
	MapmapOfStringAny *map[string]interface{}
}

// GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequestAsVideosUploadCompletePostRequest is a convenience function that returns GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest wrapped in VideosUploadCompletePostRequest
func GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequestAsVideosUploadCompletePostRequest(v *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) VideosUploadCompletePostRequest {
	return VideosUploadCompletePostRequest{
		GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest: v,
	}
}

// map[string]interface{}AsVideosUploadCompletePostRequest is a convenience function that returns map[string]interface{} wrapped in VideosUploadCompletePostRequest
func MapmapOfStringAnyAsVideosUploadCompletePostRequest(v *map[string]interface{}) VideosUploadCompletePostRequest {
	return VideosUploadCompletePostRequest{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *VideosUploadCompletePostRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
	err = newStrictDecoder(data).Decode(&dst.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest)
	if err == nil {
		jsonGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest, _ := json.Marshal(dst.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest)
		if string(jsonGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) == "{}" { // empty struct
			dst.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest = nil
		} else {
			if err = validator.Validate(dst.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest); err != nil {
				dst.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(VideosUploadCompletePostRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(VideosUploadCompletePostRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VideosUploadCompletePostRequest) MarshalJSON() ([]byte, error) {
	if src.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest != nil {
		return json.Marshal(&src.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VideosUploadCompletePostRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest != nil {
		return obj.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj VideosUploadCompletePostRequest) GetActualInstanceValue() (interface{}) {
	if obj.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest != nil {
		return *obj.GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableVideosUploadCompletePostRequest struct {
	value *VideosUploadCompletePostRequest
	isSet bool
}

func (v NullableVideosUploadCompletePostRequest) Get() *VideosUploadCompletePostRequest {
	return v.value
}

func (v *NullableVideosUploadCompletePostRequest) Set(val *VideosUploadCompletePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVideosUploadCompletePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVideosUploadCompletePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideosUploadCompletePostRequest(val *VideosUploadCompletePostRequest) *NullableVideosUploadCompletePostRequest {
	return &NullableVideosUploadCompletePostRequest{value: val, isSet: true}
}

func (v NullableVideosUploadCompletePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideosUploadCompletePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


